### ISSUE TITLE
"Too many requests" from GitHub's cache

### ISSUE THREAD

**Issue by snazy** [burrunan/gradle-cache-action#66]
I tried the `gradle-cache-action` against some refactoring of our CI workflows. The amount of time spent in our CI went quite up (up to 70 minutes), so there's the idea to split the work into separate GH workflow jobs, but should leverage Gradle caching. I ended up with nearly 20 jobs in that workflow to get CI time back to the ~20 minutes target.

However, with that amount of jobs, basically every Gradle build complains with, which I think effectively says that GitHub "doesn't like that many requests".
```
Error: Cache service responded with 429
    at /home/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:222:74
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:138:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Is there anything that could be done to issue less requests against GH's cache?

Otherwise I'd have to go back to `gradle-build-action`, with some (not so nice) hacks to collect the build-cache modifications, push those as artifacts around and so on. The `gradle-cache-action` looks so much nicer and cleaner to me.

**Comment by SettingDust** [comment]
Reproduced
Can you respect the GitHub [retry after](https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#default-limits) or just return cache missing in this situation?
