### ISSUE TITLE
Cache key collision when using matrix builds

### ISSUE THREAD

**Issue by unredundant** [burrunan/gradle-cache-action#67]
Hey :wave: I am using this action as a step inside of a matrix build (runs on windows, mac, and ubuntu runners).  I am noticing that the first build to finish has no issues, but other builds get the following error

```
Throwable: Can't reserve cache for id cb642e3fedc746b403f277cb87d02623, another job might be creating this cache: Cache already exists. Scope: refs/pull/6/merge, Key: cb642e3fedc746b403f277cb87d02623, Version: f3d7789dc46f1af3ff53c118b966da89f9f1015f5a3fb46c09f57577b24b1d7e
    at newThrowable (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:38463:27)
    at CacheProxy$putEntry$slambda.td (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:32741:15)
    at CacheProxy$putEntry$slambda.CoroutineImpl.m9 (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:40437:32)
    at CacheProxy$putEntry$slambda.CoroutineImpl.n3 (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:40460:18)
    at CancellableContinuationImpl.DispatchedTask.di (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:45351:22)
    at ScheduledMessageQueue.MessageQueue.sn (/Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:45427:23)
    at /Users/runner/work/_actions/burrunan/gradle-cache-action/v1/dist/cache-action-entrypoint.js:44597:21
    at processTicksAndRejections (node:internal/process/task_queues:[78](https://github.com/unredundant/neonctl/actions/runs/5047309187/jobs/9053999237#step:6:82):11) {
  cause: undefined
}
```

Is there a way to get the cache key to be aware of matrix inputs like operating system?

**Comment by vlsi** [comment]
There's `job-id` property.
Have you tried something like `job-id: ${{ matrix.os }}`?

**Comment by unredundant** [comment]
ah missed that in the readme, thank you!
